package com.nlpp.entity;
// Generated Apr 18, 2012 9:57:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EventPrizes generated by hbm2java
 */
@Entity
@Table(name="EventPrizes"
    ,schema="dbo"
    ,catalog="NLPP"
)
public class EventPrizes  implements java.io.Serializable {


     private int eventPrizeId;
     private Events events;
     private Serializable prizeDetail;
     private Serializable winners;

    public EventPrizes() {
    }

	
    public EventPrizes(int eventPrizeId, Events events) {
        this.eventPrizeId = eventPrizeId;
        this.events = events;
    }
    public EventPrizes(int eventPrizeId, Events events, Serializable prizeDetail, Serializable winners) {
       this.eventPrizeId = eventPrizeId;
       this.events = events;
       this.prizeDetail = prizeDetail;
       this.winners = winners;
    }
   
     @Id 
    
    @Column(name="EventPrizeID", unique=true, nullable=false)
    public int getEventPrizeId() {
        return this.eventPrizeId;
    }
    
    public void setEventPrizeId(int eventPrizeId) {
        this.eventPrizeId = eventPrizeId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EventID", nullable=false)
    public Events getEvents() {
        return this.events;
    }
    
    public void setEvents(Events events) {
        this.events = events;
    }
    
    @Column(name="PrizeDetail")
    public Serializable getPrizeDetail() {
        return this.prizeDetail;
    }
    
    public void setPrizeDetail(Serializable prizeDetail) {
        this.prizeDetail = prizeDetail;
    }
    
    @Column(name="Winners")
    public Serializable getWinners() {
        return this.winners;
    }
    
    public void setWinners(Serializable winners) {
        this.winners = winners;
    }




}


