package com.nlpp.entity;
// Generated Apr 18, 2012 9:57:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name="Events"
    ,schema="dbo"
    ,catalog="NLPP"
)
public class Events  implements java.io.Serializable {


     private int eventId;
     private EventTypes eventTypes;
     private String eventName;
     private Serializable topic;
     private Serializable speakers;
     private Serializable guests;
     private Serializable criteria;
     private Serializable termsAndConditions;
     private Serializable location;
     private Date conductingDate;
     private Double fees;
     private int numberOfParticipants;
     private Set eventPrizeses = new HashSet(0);
     private Set eventEnrollmentses = new HashSet(0);

    public Events() {
    }

	
    public Events(int eventId, EventTypes eventTypes, String eventName, Serializable topic, Serializable location, Date conductingDate, int numberOfParticipants) {
        this.eventId = eventId;
        this.eventTypes = eventTypes;
        this.eventName = eventName;
        this.topic = topic;
        this.location = location;
        this.conductingDate = conductingDate;
        this.numberOfParticipants = numberOfParticipants;
    }
    public Events(int eventId, EventTypes eventTypes, String eventName, Serializable topic, Serializable speakers, Serializable guests, Serializable criteria, Serializable termsAndConditions, Serializable location, Date conductingDate, Double fees, int numberOfParticipants, Set eventPrizeses, Set eventEnrollmentses) {
       this.eventId = eventId;
       this.eventTypes = eventTypes;
       this.eventName = eventName;
       this.topic = topic;
       this.speakers = speakers;
       this.guests = guests;
       this.criteria = criteria;
       this.termsAndConditions = termsAndConditions;
       this.location = location;
       this.conductingDate = conductingDate;
       this.fees = fees;
       this.numberOfParticipants = numberOfParticipants;
       this.eventPrizeses = eventPrizeses;
       this.eventEnrollmentses = eventEnrollmentses;
    }
   
     @Id 
    
    @Column(name="EventID", unique=true, nullable=false)
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EventType", nullable=false)
    public EventTypes getEventTypes() {
        return this.eventTypes;
    }
    
    public void setEventTypes(EventTypes eventTypes) {
        this.eventTypes = eventTypes;
    }
    
    @Column(name="EventName", nullable=false, length=100)
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    
    @Column(name="Topic", nullable=false)
    public Serializable getTopic() {
        return this.topic;
    }
    
    public void setTopic(Serializable topic) {
        this.topic = topic;
    }
    
    @Column(name="Speakers")
    public Serializable getSpeakers() {
        return this.speakers;
    }
    
    public void setSpeakers(Serializable speakers) {
        this.speakers = speakers;
    }
    
    @Column(name="Guests")
    public Serializable getGuests() {
        return this.guests;
    }
    
    public void setGuests(Serializable guests) {
        this.guests = guests;
    }
    
    @Column(name="Criteria")
    public Serializable getCriteria() {
        return this.criteria;
    }
    
    public void setCriteria(Serializable criteria) {
        this.criteria = criteria;
    }
    
    @Column(name="TermsAndConditions")
    public Serializable getTermsAndConditions() {
        return this.termsAndConditions;
    }
    
    public void setTermsAndConditions(Serializable termsAndConditions) {
        this.termsAndConditions = termsAndConditions;
    }
    
    @Column(name="Location", nullable=false)
    public Serializable getLocation() {
        return this.location;
    }
    
    public void setLocation(Serializable location) {
        this.location = location;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="ConductingDate", nullable=false, length=10)
    public Date getConductingDate() {
        return this.conductingDate;
    }
    
    public void setConductingDate(Date conductingDate) {
        this.conductingDate = conductingDate;
    }
    
    @Column(name="Fees", precision=53, scale=0)
    public Double getFees() {
        return this.fees;
    }
    
    public void setFees(Double fees) {
        this.fees = fees;
    }
    
    @Column(name="NumberOfParticipants", nullable=false)
    public int getNumberOfParticipants() {
        return this.numberOfParticipants;
    }
    
    public void setNumberOfParticipants(int numberOfParticipants) {
        this.numberOfParticipants = numberOfParticipants;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="events")
    public Set getEventPrizeses() {
        return this.eventPrizeses;
    }
    
    public void setEventPrizeses(Set eventPrizeses) {
        this.eventPrizeses = eventPrizeses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="events")
    public Set getEventEnrollmentses() {
        return this.eventEnrollmentses;
    }
    
    public void setEventEnrollmentses(Set eventEnrollmentses) {
        this.eventEnrollmentses = eventEnrollmentses;
    }




}


