package com.nlpp.entity;
// Generated Apr 18, 2012 9:57:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EventTypes generated by hbm2java
 */
@Entity
@Table(name="EventTypes"
    ,schema="dbo"
    ,catalog="NLPP"
    , uniqueConstraints = @UniqueConstraint(columnNames="EventTypeName") 
)
public class EventTypes  implements java.io.Serializable {


     private int eventTypeId;
     private Serializable eventTypeName;
     private Serializable description;
     private Set userses = new HashSet(0);
     private Set eventses = new HashSet(0);

    public EventTypes() {
    }

	
    public EventTypes(int eventTypeId, Serializable eventTypeName) {
        this.eventTypeId = eventTypeId;
        this.eventTypeName = eventTypeName;
    }
    public EventTypes(int eventTypeId, Serializable eventTypeName, Serializable description, Set userses, Set eventses) {
       this.eventTypeId = eventTypeId;
       this.eventTypeName = eventTypeName;
       this.description = description;
       this.userses = userses;
       this.eventses = eventses;
    }
   
     @Id 
    
    @Column(name="EventTypeID", unique=true, nullable=false)
    public int getEventTypeId() {
        return this.eventTypeId;
    }
    
    public void setEventTypeId(int eventTypeId) {
        this.eventTypeId = eventTypeId;
    }
    
    @Column(name="EventTypeName", unique=true, nullable=false)
    public Serializable getEventTypeName() {
        return this.eventTypeName;
    }
    
    public void setEventTypeName(Serializable eventTypeName) {
        this.eventTypeName = eventTypeName;
    }
    
    @Column(name="Description")
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="eventTypeses")
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="eventTypes")
    public Set getEventses() {
        return this.eventses;
    }
    
    public void setEventses(Set eventses) {
        this.eventses = eventses;
    }




}


