package com.nlpp.entity;
// Generated Apr 18, 2012 9:57:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentType generated by hbm2java
 */
@Entity
@Table(name="PaymentType"
    ,schema="dbo"
    ,catalog="NLPP"
)
public class PaymentType  implements java.io.Serializable {


     private int paymentTypeId;
     private String paymentTypeName;
     private Set eventEnrollmentses = new HashSet(0);

    public PaymentType() {
    }

	
    public PaymentType(int paymentTypeId, String paymentTypeName) {
        this.paymentTypeId = paymentTypeId;
        this.paymentTypeName = paymentTypeName;
    }
    public PaymentType(int paymentTypeId, String paymentTypeName, Set eventEnrollmentses) {
       this.paymentTypeId = paymentTypeId;
       this.paymentTypeName = paymentTypeName;
       this.eventEnrollmentses = eventEnrollmentses;
    }
   
     @Id 
    
    @Column(name="PaymentTypeID", unique=true, nullable=false)
    public int getPaymentTypeId() {
        return this.paymentTypeId;
    }
    
    public void setPaymentTypeId(int paymentTypeId) {
        this.paymentTypeId = paymentTypeId;
    }
    
    @Column(name="PaymentTypeName", nullable=false, length=100)
    public String getPaymentTypeName() {
        return this.paymentTypeName;
    }
    
    public void setPaymentTypeName(String paymentTypeName) {
        this.paymentTypeName = paymentTypeName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="paymentType")
    public Set getEventEnrollmentses() {
        return this.eventEnrollmentses;
    }
    
    public void setEventEnrollmentses(Set eventEnrollmentses) {
        this.eventEnrollmentses = eventEnrollmentses;
    }




}


