package com.nlpp.entity;
// Generated Apr 18, 2012 9:57:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="Users"
    ,schema="dbo"
    ,catalog="NLPP"
)
public class Users  implements java.io.Serializable {


     private String username;
     private String password;
     private boolean isAdmin;
     private Serializable fullName;
     private boolean gender;
     private Date dateOfBirth;
     private Serializable address;
     private String phone;
     private String email;
     private Date joinDate;
     private Set eventEnrollmentses = new HashSet(0);
     private Set eventTypeses = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, String password, boolean isAdmin, Serializable fullName, boolean gender, Date dateOfBirth, String email, Date joinDate) {
        this.username = username;
        this.password = password;
        this.isAdmin = isAdmin;
        this.fullName = fullName;
        this.gender = gender;
        this.dateOfBirth = dateOfBirth;
        this.email = email;
        this.joinDate = joinDate;
    }
    public Users(String username, String password, boolean isAdmin, Serializable fullName, boolean gender, Date dateOfBirth, Serializable address, String phone, String email, Date joinDate, Set eventEnrollmentses, Set eventTypeses) {
       this.username = username;
       this.password = password;
       this.isAdmin = isAdmin;
       this.fullName = fullName;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.joinDate = joinDate;
       this.eventEnrollmentses = eventEnrollmentses;
       this.eventTypeses = eventTypeses;
    }
   
     @Id 
    
    @Column(name="Username", unique=true, nullable=false, length=30)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="Password", nullable=false, length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="IsAdmin", nullable=false)
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    
    @Column(name="FullName", nullable=false)
    public Serializable getFullName() {
        return this.fullName;
    }
    
    public void setFullName(Serializable fullName) {
        this.fullName = fullName;
    }
    
    @Column(name="Gender", nullable=false)
    public boolean isGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DateOfBirth", nullable=false, length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    
    @Column(name="Address")
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    
    @Column(name="Phone", length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="Email", nullable=false, length=30)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="JoinDate", nullable=false, length=10)
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set getEventEnrollmentses() {
        return this.eventEnrollmentses;
    }
    
    public void setEventEnrollmentses(Set eventEnrollmentses) {
        this.eventEnrollmentses = eventEnrollmentses;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="EventNotifications", schema="dbo", catalog="NLPP", joinColumns = { 
        @JoinColumn(name="Username", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="EventType", nullable=false, updatable=false) })
    public Set getEventTypeses() {
        return this.eventTypeses;
    }
    
    public void setEventTypeses(Set eventTypeses) {
        this.eventTypeses = eventTypeses;
    }




}


