package com.nlpp.domain;
// Generated Sep 5, 2011 11:57:48 PM by Hibernate Tools 3.2.1.GA



/**
 * EmailRecieverEventCategory generated by hbm2java
 */
public class EmailRecieverEventCategory  implements java.io.Serializable {


     private int erecid;
     private Category category;
     private Person person;

    public EmailRecieverEventCategory() {
    }

	
    public EmailRecieverEventCategory(int erecid) {
        this.erecid = erecid;
    }
    public EmailRecieverEventCategory(int erecid, Category category, Person person) {
       this.erecid = erecid;
       this.category = category;
       this.person = person;
    }
   
    public int getErecid() {
        return this.erecid;
    }
    
    public void setErecid(int erecid) {
        this.erecid = erecid;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }




}


