package com.nlpp.domain;
// Generated Sep 5, 2011 11:57:48 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * EnrollEvent generated by hbm2java
 */
public class EnrollEvent  implements java.io.Serializable {


     private int enrollEventId;
     private Events events;
     private Person person;
     private int isPayment;
     private Date dateReg;
     private Date datePay;
     private BigDecimal payMoney;
     private int isWin;
     private int visiable;
     private boolean expires;

    public EnrollEvent() {
    }

	
    public EnrollEvent(int enrollEventId, int isPayment, int isWin, int visiable) {
        this.enrollEventId = enrollEventId;
        this.isPayment = isPayment;
        this.isWin = isWin;
        this.visiable = visiable;
    }
    public EnrollEvent(int enrollEventId, Events events, Person person, int isPayment, Date dateReg, Date datePay, BigDecimal payMoney, int isWin, int visiable) {
       this.enrollEventId = enrollEventId;
       this.events = events;
       this.person = person;
       this.isPayment = isPayment;
       this.dateReg = dateReg;
       this.datePay = datePay;
       this.payMoney = payMoney;
       this.isWin = isWin;
       this.visiable = visiable;
    }
   
    public int getEnrollEventId() {
        return this.enrollEventId;
    }
    
    public void setEnrollEventId(int enrollEventId) {
        this.enrollEventId = enrollEventId;
    }
    public Events getEvents() {
        return this.events;
    }
    
    public void setEvents(Events events) {
        this.events = events;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public int getIsPayment() {
        return this.isPayment;
    }
    
    public void setIsPayment(int isPayment) {
        this.isPayment = isPayment;
    }
    public Date getDateReg() {
        return this.dateReg;
    }
    
    public void setDateReg(Date dateReg) {
        this.dateReg = dateReg;
    }
    public Date getDatePay() {
        return this.datePay;
    }
    
    public void setDatePay(Date datePay) {
        this.datePay = datePay;
    }
    public BigDecimal getPayMoney() {
        return this.payMoney;
    }
    
    public void setPayMoney(BigDecimal payMoney) {
        this.payMoney = payMoney;
    }
    public int getIsWin() {
        return this.isWin;
    }
    
    public void setIsWin(int isWin) {
        this.isWin = isWin;
    }
    public int getVisiable() {
        return this.visiable;
    }
    
    public void setVisiable(int visiable) {
        this.visiable = visiable;
    }

    public boolean isExpires() {
        return expires;
    }

    public void setExpires(boolean expires) {
        this.expires = expires;
    }
}


