package com.nlpp.domain;
// Generated Sep 5, 2011 11:57:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Events generated by hbm2java
 */
public class Events implements java.io.Serializable {

    private int eventId;
    private Category category;
    private String eventName;
    private Date dateCreate;
    private Date timeEvent;
    private Date deadline;
    private String address;
    private String images;
    private String description;
    private String details;
    private double price;
    private int countView;
    private int visiable;
    private Set<EnrollEvent> enrollEvents = new HashSet<EnrollEvent>(0);
    private Set<Comment> comments = new HashSet<Comment>(0);

    public Events() {
    }

    public Events(int eventId, String eventName, Date dateCreate, Date timeEvent, Date deadline, String images, String description, String details, double price, int countView, int visiable) {
        this.eventId = eventId;
        this.eventName = eventName;
        this.dateCreate = dateCreate;
        this.timeEvent = timeEvent;
        this.deadline = deadline;
        this.images = images;
        this.description = description;
        this.details = details;
        this.price = price;
        this.countView = countView;
        this.visiable = visiable;
    }

    public Events(int eventId, Category category, String eventName, Date dateCreate, Date timeEvent, Date deadline, String address, String images, String description, String details, double price, int countView, int visiable) {
        this.eventId = eventId;
        this.category = category;
        this.eventName = eventName;
        this.dateCreate = dateCreate;
        this.timeEvent = timeEvent;
        this.deadline = deadline;
        this.address = address;
        this.images = images;
        this.description = description;
        this.details = details;
        this.price = price;
        this.countView = countView;
        this.visiable = visiable;
    }

    public int getEventId() {
        return this.eventId;
    }

    public void setEventId(int eventId) {
        this.eventId = eventId;
    }

    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public String getEventName() {
        return this.eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    public Date getDateCreate() {
        return this.dateCreate;
    }

    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    public Date getTimeEvent() {
        return this.timeEvent;
    }

    public void setTimeEvent(Date timeEvent) {
        this.timeEvent = timeEvent;
    }

    public Date getDeadline() {
        return this.deadline;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    public String getImages() {
        return this.images;
    }

    public void setImages(String images) {
        this.images = images;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDetails() {
        return this.details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public int getCountView() {
        return this.countView;
    }

    public void setCountView(int countView) {
        this.countView = countView;
    }

    public int getVisiable() {
        return this.visiable;
    }

    public void setVisiable(int visiable) {
        this.visiable = visiable;
    }

    public Set<EnrollEvent> getEnrollEvents() {
        return this.enrollEvents;
    }

    public void setEnrollEvents(Set<EnrollEvent> enrollEvents) {
        this.enrollEvents = enrollEvents;
    }

    public Set<Comment> getComments() {
        return this.comments;
    }

    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
}
