package com.nlpp.domain;
// Generated Apr 9, 2012 11:01:15 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * EventPrizes generated by hbm2java
 */
public class EventPrizes  implements java.io.Serializable {


     private int eventPrizeId;
     private Events events;
     private Serializable prizeDetail;
     private Serializable winners;

    public EventPrizes() {
    }

	
    public EventPrizes(int eventPrizeId, Events events) {
        this.eventPrizeId = eventPrizeId;
        this.events = events;
    }
    public EventPrizes(int eventPrizeId, Events events, Serializable prizeDetail, Serializable winners) {
       this.eventPrizeId = eventPrizeId;
       this.events = events;
       this.prizeDetail = prizeDetail;
       this.winners = winners;
    }
   
    public int getEventPrizeId() {
        return this.eventPrizeId;
    }
    
    public void setEventPrizeId(int eventPrizeId) {
        this.eventPrizeId = eventPrizeId;
    }
    public Events getEvents() {
        return this.events;
    }
    
    public void setEvents(Events events) {
        this.events = events;
    }
    public Serializable getPrizeDetail() {
        return this.prizeDetail;
    }
    
    public void setPrizeDetail(Serializable prizeDetail) {
        this.prizeDetail = prizeDetail;
    }
    public Serializable getWinners() {
        return this.winners;
    }
    
    public void setWinners(Serializable winners) {
        this.winners = winners;
    }




}


