package com.nlpp.domain;
// Generated Apr 9, 2012 11:01:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EventEnrollments generated by hbm2java
 */
public class EventEnrollments  implements java.io.Serializable {


     private EventEnrollmentsId id;
     private Events events;
     private Users users;
     private PaymentType paymentType;
     private boolean isPaid;
     private Date dateOfEnrollment;
     private Date dateOfPayment;

    public EventEnrollments() {
    }

	
    public EventEnrollments(EventEnrollmentsId id, Events events, Users users, PaymentType paymentType, boolean isPaid, Date dateOfEnrollment) {
        this.id = id;
        this.events = events;
        this.users = users;
        this.paymentType = paymentType;
        this.isPaid = isPaid;
        this.dateOfEnrollment = dateOfEnrollment;
    }
    public EventEnrollments(EventEnrollmentsId id, Events events, Users users, PaymentType paymentType, boolean isPaid, Date dateOfEnrollment, Date dateOfPayment) {
       this.id = id;
       this.events = events;
       this.users = users;
       this.paymentType = paymentType;
       this.isPaid = isPaid;
       this.dateOfEnrollment = dateOfEnrollment;
       this.dateOfPayment = dateOfPayment;
    }
   
    public EventEnrollmentsId getId() {
        return this.id;
    }
    
    public void setId(EventEnrollmentsId id) {
        this.id = id;
    }
    public Events getEvents() {
        return this.events;
    }
    
    public void setEvents(Events events) {
        this.events = events;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public PaymentType getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }
    public boolean isIsPaid() {
        return this.isPaid;
    }
    
    public void setIsPaid(boolean isPaid) {
        this.isPaid = isPaid;
    }
    public Date getDateOfEnrollment() {
        return this.dateOfEnrollment;
    }
    
    public void setDateOfEnrollment(Date dateOfEnrollment) {
        this.dateOfEnrollment = dateOfEnrollment;
    }
    public Date getDateOfPayment() {
        return this.dateOfPayment;
    }
    
    public void setDateOfPayment(Date dateOfPayment) {
        this.dateOfPayment = dateOfPayment;
    }




}


