package com.nlpp.domain;
// Generated Apr 9, 2012 11:01:15 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String username;
     private String password;
     private boolean isAdmin;
     private Serializable fullName;
     private boolean gender;
     private Date dateOfBirth;
     private Serializable address;
     private String phone;
     private String email;
     private Date joinDate;
     private Set eventEnrollmentses = new HashSet(0);
     private Set eventTypeses = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, String password, boolean isAdmin, Serializable fullName, boolean gender, Date dateOfBirth, String email, Date joinDate) {
        this.username = username;
        this.password = password;
        this.isAdmin = isAdmin;
        this.fullName = fullName;
        this.gender = gender;
        this.dateOfBirth = dateOfBirth;
        this.email = email;
        this.joinDate = joinDate;
    }
    public Users(String username, String password, boolean isAdmin, Serializable fullName, boolean gender, Date dateOfBirth, Serializable address, String phone, String email, Date joinDate, Set eventEnrollmentses, Set eventTypeses) {
       this.username = username;
       this.password = password;
       this.isAdmin = isAdmin;
       this.fullName = fullName;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.joinDate = joinDate;
       this.eventEnrollmentses = eventEnrollmentses;
       this.eventTypeses = eventTypeses;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Serializable getFullName() {
        return this.fullName;
    }
    
    public void setFullName(Serializable fullName) {
        this.fullName = fullName;
    }
    public boolean isGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }
    public Set getEventEnrollmentses() {
        return this.eventEnrollmentses;
    }
    
    public void setEventEnrollmentses(Set eventEnrollmentses) {
        this.eventEnrollmentses = eventEnrollmentses;
    }
    public Set getEventTypeses() {
        return this.eventTypeses;
    }
    
    public void setEventTypeses(Set eventTypeses) {
        this.eventTypeses = eventTypeses;
    }




}


