package com.nlpp.entity;
// Generated Apr 18, 2012 9:57:40 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventEnrollmentsId generated by hbm2java
 */
@Embeddable
public class EventEnrollmentsId  implements java.io.Serializable {


     private int eventId;
     private String username;

    public EventEnrollmentsId() {
    }

    public EventEnrollmentsId(int eventId, String username) {
       this.eventId = eventId;
       this.username = username;
    }
   

    @Column(name="EventID", nullable=false)
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }

    @Column(name="Username", nullable=false, length=30)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventEnrollmentsId) ) return false;
		 EventEnrollmentsId castOther = ( EventEnrollmentsId ) other; 
         
		 return (this.getEventId()==castOther.getEventId())
 && ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEventId();
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         return result;
   }   


}


